'use strict';
const icons={grid:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',water:'<path d="M12 3C9 7 5.5 10.3 5.5 14a6.5 6.5 0 0 0 13 0C18.5 10.3 15 7 12 3Z"/><path d="M9 14a3 3 0 0 0 3 3"/>',leaf:'<path d="M20 4c-8-2-16 1-16 8a7 7 0 0 0 12 5c3-3 2-8 4-13Z"/><path d="m4 21 11-12M9 16v-5m0 5h5"/>',health:'<path d="M9 3h6v6h6v6h-6v6H9v-6H3V9h6Z"/>',book:'<path d="M12 6c-3-2-6-2-9-1v15c3-1 6-1 9 1 3-2 6-2 9-1V5c-3-1-6-1-9 1v15"/>',cloud:'<path d="M7 18h10a5 5 0 0 0 1-9.9 6.5 6.5 0 0 0-12.1-1A5.5 5.5 0 0 0 7 18Z"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10h.01"/>',village:'<path d="m2 11 6-6 6 6M4 9v11h8V9m1-5h7v16h-5M7 16h2m7-8h1m-1 4h1m-1 4h1"/>',layers:'<path d="m12 3 10 5-10 5L2 8Zm-10 9 10 5 10-5M2 16l10 5 10-5"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',refresh:'<path d="M20 7v5h-5M4 17v-5h5"/><path d="M6 7a7 7 0 0 1 12 0l2 5M4 12l2 5a7 7 0 0 0 12 0"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',check:'<path d="m5 12 4 4L19 6"/>',flask:'<path d="M9 3h6m-5 0v6l-6 10a1.4 1.4 0 0 0 1 2h14a1.4 1.4 0 0 0 1-2L14 9V3M8 14h8"/>',server:'<rect x="3" y="3" width="18" height="7" rx="2"/><rect x="3" y="14" width="18" height="7" rx="2"/><path d="M7 6.5h.01M7 17.5h.01M15 6.5h3M15 17.5h3"/>',monitor:'<rect x="3" y="3" width="18" height="13" rx="2"/><path d="M12 16v5m-5 0h10"/>',globe:'<circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/>',code:'<path d="m8 7-5 5 5 5m8-10 5 5-5 5M14 4l-4 16"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1 1m12 12 1 1M5 19l1-1M18 6l1-1"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>'};
const icon=name=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${icons[name]||icons.grid}</svg>`;
const services=[{id:'water',name:'Water supply',short:'Water',icon:'water',color:'#3675ed',soft:'#edf3ff',value:78,unit:'%',metric:'Tank capacity',status:'Good',detail:'Supply is within the demo target.',trend:[62,68,65,76,72,81,78]},{id:'agriculture',name:'Agriculture',short:'Agriculture',icon:'leaf',color:'#31865b',soft:'#edf7f0',value:65,unit:'%',metric:'Soil moisture',status:'Sunny',detail:'Sunny weather in the demo dataset.',trend:[55,58,54,64,59,67,65]},{id:'healthcare',name:'Healthcare',short:'Healthcare',icon:'health',color:'#8a63cb',soft:'#f3effb',value:'Available',unit:'',metric:'Doctor availability',status:'Available',detail:'Sample clinic availability.',trend:[74,80,78,86,80,83,88]},{id:'education',name:'Education',short:'Education',icon:'book',color:'#c18b2e',soft:'#fff7e9',value:92,unit:'%',metric:'Student attendance',status:'Connected',detail:'Sample school attendance.',trend:[86,89,87,92,90,94,92]}];
const state={page:'overview',range:7,revision:0,updated:new Date()};
const main=document.querySelector('#main');
const titles={overview:'Overview',water:'Water supply',agriculture:'Agriculture',healthcare:'Healthcare',education:'Education',architecture:'Cloud architecture',about:'About this project'};
const serviceStyle=s=>`--service:${s.color};--soft:${s.soft}`;
function drawIcons(){document.querySelectorAll('[data-icon]').forEach(el=>{el.innerHTML=icon(el.dataset.icon);});}
function heading(eyebrow,title,description,refresh=true){return `<div class="page-heading"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${description}</p></div>${refresh?`<div class="heading-actions"><button class="button" data-action="refresh" title="Update the simulated readings" aria-label="Update demo readings">${icon('refresh')}Update demo</button></div>`:''}</div>`;}
function metric(s){return `<a class="metric" href="#${s.id}" style="${serviceStyle(s)}">
  <div class="metric-top"><span class="service-icon">${icon(s.icon)}</span><span>${s.name}</span><span class="metric-arrow">${icon('arrow')}</span></div>
  <div class="metric-number ${s.id==='healthcare'?'metric-word':''}">${s.value}<small>${s.unit}</small></div>
  <div class="metric-subtitle">${s.metric}</div>
  <div class="metric-bottom"><span class="tag">${s.status}</span><span>View details</span></div>
</a>`;}
function lineChart(series,large=false){const w=620,h=235,left=42,right=600,top=18,bottom=188;const count=state.range===7?7:15;const points=series.map(s=>Array.from({length:count},(_,i)=>{if(count===7)return s.trend[i];return Math.max(25,Math.min(98,s.trend[i%7]+Math.round(Math.sin(i*1.7)*4)));}));const path=values=>values.map((v,i)=>`${i?'L':'M'}${(left+i*(right-left)/(count-1)).toFixed(2)},${(bottom-v*(bottom-top)/100).toFixed(2)}`).join(' ');const rows=[0,25,50,75,100].map(v=>`<line x1="${left}" y1="${bottom-v*(bottom-top)/100}" x2="${right}" y2="${bottom-v*(bottom-top)/100}" stroke="#eaf0f5" stroke-dasharray="3 5"/><text x="${left-12}" y="${bottom-v*(bottom-top)/100+4}" text-anchor="end" fill="#8490a4" font-size="10">${v}%</text>`).join('');const dayLabels=state.range===7?['Day 1','Day 2','Day 3','Day 4','Day 5','Day 6','Today']:['Day 1','Day 6','Day 11','Day 16','Day 21','Day 26','Day 30'];const labels=dayLabels.map((v,i)=>`<text x="${left+i*(right-left)/6}" y="214" text-anchor="middle" fill="#8490a4" font-size="10">${v}</text>`).join('');const lines=series.map((s,i)=>`${i===0?`<path d="${path(points[i])} L${right},${bottom} L${left},${bottom} Z" fill="${s.color}" opacity=".06"/>`:''}<path d="${path(points[i])}" fill="none" stroke="${s.color}" stroke-width="2.7" stroke-linejoin="round"/>${points[i].map((v,j)=>`<circle cx="${left+j*(right-left)/(count-1)}" cy="${bottom-v*(bottom-top)/100}" r="3" fill="white" stroke="${s.color}" stroke-width="1.8"><title>${s.short}: ${v}% · sample ${j+1}</title></circle>`).join('')}`).join('');return `<div class="chart-wrap"><svg class="line-chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="Simulated ${state.range}-day trend: ${series.map(s=>s.metric).join(', ')}">${rows}${lines}${labels}</svg></div>`;}
function rangeControl(){return `<div class="segments" role="group" aria-label="Chart period"><button data-range="7" class="${state.range===7?'selected':''}" aria-pressed="${state.range===7}">7 days</button><button data-range="30" class="${state.range===30?'selected':''}" aria-pressed="${state.range===30}">30 days</button></div>`;}
function overview(){return `
  <div class="overview-heading">
    <div><div class="eyebrow">YOUR CONNECTED COMMUNITY</div><h1>Village overview</h1><p>Four essential services. One shared view.</p></div>
    <button class="button primary" data-action="refresh" aria-label="Update demo readings">${icon('refresh')}Update demo</button>
  </div>
  <div class="overview-context"><span>${icon('flask')}Simulated village data</span><time>Updated ${state.updated.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time></div>
  <div class="overview-workspace">
    <section class="service-summary" aria-labelledby="services-title">
      <div class="section-heading"><h2 id="services-title">Village services</h2><span>04 services</span></div>
      <div class="metrics">${services.map(metric).join('')}</div>
    </section>
    <section class="panel overview-chart" aria-labelledby="trends-title">
      <div class="panel-heading"><div><div class="eyebrow">SERVICE ACTIVITY</div><h2 id="trends-title">The bigger picture</h2><p>Water levels and attendance over time</p></div>${rangeControl()}</div>
      <div class="chart-key">${[services[0],services[3]].map(s=>`<span><i class="swatch" style="--series:${s.color}"></i>${s.metric}</span>`).join('')}</div>
      ${lineChart([services[0],services[3]])}
      <div class="chart-foot"><span>Last ${state.range} days · Sample readings</span><span>Percentage (%)</span></div>
    </section>
  </div>
  <section class="panel wide-panel">
    <div class="panel-heading"><div><h2>Service directory</h2><p>Current readings and a closer look at each service.</p></div><span class="directory-count">4 services</span></div>
    <div class="table-wrap"><table><thead><tr><th scope="col">Service</th><th scope="col">What it monitors</th><th scope="col">Current reading</th><th scope="col">Status</th><th scope="col"><span class="sr-only">Details</span></th></tr></thead>
    <tbody>${services.map(s=>`<tr style="${serviceStyle(s)}"><td><a class="table-service" href="#${s.id}"><span class="service-icon">${icon(s.icon)}</span><strong>${s.name}</strong></a></td><td>${s.metric}</td><td><strong>${s.value}${s.unit}</strong></td><td><span class="tag">${s.status}</span></td><td><a class="link-button" href="#${s.id}" aria-label="Explore ${s.name}">Explore ${icon('arrow')}</a></td></tr>`).join('')}</tbody></table></div>
    <p class="table-message">Demo readings illustrate the interface; no live village systems are connected.</p>
  </section>
  <section class="project-note"><div><span class="note-icon">${icon('cloud')}</span><div><h2>Behind the connected village</h2><p>Explore how this project brings essential services together through the cloud.</p></div></div><a class="button" href="#architecture">View architecture ${icon('arrow')}</a></section>
`;}
const detailContent={
water:{intro:'Follow the supply, quality, and storage of the village’s water.',label:'Tank level',description:'A sample storage reading for the village’s main water tank.',facts:[['Water quality','Good','Illustrative quality status'],['Daily consumption','1,250 L','Sample daily usage'],['Next supply','06:00 AM','Example supply schedule']],chartTitle:'Water storage trend',chartDescription:'Sample tank levels over the selected period',notes:[['Storage','The demo tank is above the 40% low-level threshold.'],['Water quality','“Good” is a sample label, not a laboratory result.'],['Supply schedule','The displayed time illustrates a scheduled water supply.']],noteTitle:'Supply notes'},
agriculture:{intro:'Understand field conditions with a shared view of soil and weather.',label:'Soil moisture',description:'An example moisture reading for a village agricultural plot.',facts:[['Temperature','30°C','Sample weather reading'],['Weather','Sunny','Illustrative conditions'],['Crop stage','Growing','Example field status']],chartTitle:'Soil moisture trend',chartDescription:'Sample moisture readings over the selected period',notes:[['Field conditions','The demo field shows a moisture reading above 50%.'],['Weather','Weather values are simulated and do not use a forecast service.'],['Irrigation','Real irrigation decisions need local soil, crop, and weather measurements.']],noteTitle:'Field notes'},
healthcare:{intro:'See a simple snapshot of the village clinic’s availability.',label:'Doctor availability',description:'Example availability for a community health centre.',facts:[['Clinic status','Open','Sample service status'],['Clinic hours','9 AM–4 PM','Example opening hours'],['Next session','Tomorrow','Illustrative schedule']],notes:[['General consultation','An example service offered by the community clinic.'],['Basic health checks','A sample service category for the village dashboard.'],['Community outreach','A place for local programme availability in a connected system.']],noteTitle:'Example clinic services'},
education:{intro:'Follow attendance and digital access in the village learning centre.',label:'Student attendance',description:'An example attendance rate for the village school.',facts:[['Internet','Connected','Sample connection status'],['Learning centre','Open','Example service availability'],['School session','In progress','Illustrative class status']],chartTitle:'Attendance trend',chartDescription:'Sample attendance over the selected period',notes:[['Attendance','The sample attendance rate is above the 85% demonstration target.'],['Digital learning','The connection status shows how online access could be monitored.'],['Student privacy','No student names, records, or personal information are collected.']],noteTitle:'Learning centre notes'}
};
function factCards(items,s){return `<div class="detail-facts">${items.map(([label,value,note])=>`<div class="fact-card"><span>${label}</span><strong style="color:${s.color}">${value}</strong><small>${note}</small></div>`).join('')}</div>`;}
function servicePage(s){const d=detailContent[s.id];const quantitative=typeof s.value==='number';const headline=quantitative?`${s.value}<small>${s.unit}</small>`:'Available';return `${heading('VILLAGE SERVICES',s.name,d.intro)}<div class="detail-lead" style="${serviceStyle(s)}"><section class="reading-card"><div class="reading-title"><span class="service-icon">${icon(s.icon)}</span><span class="tag">${s.status}</span></div><h2>${d.label}</h2><div class="reading-value ${quantitative?'':'reading-word'}">${headline}</div>${quantitative?`<div class="reading-track" role="meter" aria-label="${d.label}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${s.value}"><span style="width:${s.value}%"></span></div><div class="track-labels"><span>0%</span><span>100%</span></div>`:`<div class="availability-row">${icon('check')}Sample doctor on duty</div>`}<p>${d.description}</p></section>${factCards(d.facts,s)}</div><div class="two-col"><section class="panel">${quantitative?`<div class="panel-heading"><div><h2>${d.chartTitle}</h2><p>${d.chartDescription}</p></div>${rangeControl()}</div><div class="chart-key"><span><i class="swatch" style="--series:${s.color}"></i>${d.label}</span></div>${lineChart([s])}<div class="chart-foot"><span>Last ${state.range} days · Simulated readings</span><span>Percentage</span></div>`:`<div class="panel-heading"><div><h2>Clinic availability</h2><p>A demonstration of a weekly service schedule</p></div></div><div class="clinic-schedule"><div class="schedule-row"><span>Monday – Friday</span><strong>9:00 AM – 4:00 PM</strong><span class="tag">Regular clinic</span></div><div class="schedule-row"><span>Saturday</span><strong>9:00 AM – 12:00 PM</strong><span class="tag">Morning clinic</span></div><div class="schedule-row"><span>Sunday</span><strong>Closed</strong><span class="tag neutral">No regular clinic</span></div></div><div class="clinic-notice">${icon('info')}This is an example timetable, not a real healthcare directory or appointment service.</div>`}</section><section class="panel"><div class="panel-heading"><div><h2>${d.noteTitle}</h2><p>Context behind the sample readings</p></div></div><div class="notes-list">${d.notes.map(([label,description],i)=>`<div class="note-row"><span class="note-number">0${i+1}</span><div><h3>${label}</h3><p>${description}</p></div></div>`).join('')}</div></section></div><div class="demo-disclaimer">${icon('flask')}<p><strong>Made for demonstration.</strong> This page uses simulated data. It does not receive live sensor readings or connect to a real ${s.id==='healthcare'?'clinic':s.id==='education'?'school':'village service'}.</p></div><a class="back-link" href="#overview">← Back to village overview</a>`;}
function architecturePage(){const flow=[['monitor','01','Browser','A person opens the village dashboard.'],['globe','02','Internet','The request travels over a secure connection.'],['cloud','03','Cloud hosting','The website is delivered to the browser.'],['grid','04','Shared dashboard','Village services appear in a single interface.']];return `${heading('BEHIND THE WORKSPACE','A village, connected.','Explore the cloud concepts behind this educational prototype.',false)}<section class="architecture-banner"><span>${icon('cloud')}</span><div><div class="eyebrow">CLOUD COMPUTING, MADE TANGIBLE</div><h2>Access services through one browser.</h2><p>A shared web interface can make village information easier to find and understand.</p></div></section><section class="panel architecture-flow"><div class="panel-heading"><div><h2>How this website works</h2><p>The path from your device to the dashboard</p></div><span class="tag neutral">CURRENT PROTOTYPE</span></div><div class="flow-grid">${flow.map(([symbol,num,title,description])=>`<div class="flow-step"><span class="flow-number">${num}</span><div class="flow-icon">${icon(symbol)}</div><h3>${title}</h3><p>${description}</p></div>`).join('')}</div></section><div class="architecture-columns"><section class="panel information-panel"><div class="panel-heading"><div><h2>In this version</h2><p>What the prototype actually does</p></div></div><ul class="feature-list"><li>${icon('check')}Displays four services using a sample dataset.</li><li>${icon('check')}Renders charts and service pages in your browser.</li><li>${icon('check')}Lets you explore demo periods and update sample readings.</li><li>${icon('check')}Works on mobile and desktop without a login.</li></ul></section><section class="panel information-panel future-panel"><div class="panel-heading"><div><h2>A future connected system</h2><p>Concepts beyond this demonstration</p></div></div><ul class="feature-list"><li>${icon('water')}Sensors could send water, soil, and weather measurements.</li><li>${icon('server')}A backend and database could store historical readings.</li><li>${icon('health')}Authorised staff could update service availability.</li><li>${icon('info')}Access controls could protect sensitive records.</li></ul></section></div><div class="demo-disclaimer">${icon('info')}<p>The sensor network, database, and staff accounts are proposed extensions. They are not connected to this demo.</p></div>`;}
function aboutPage(){return `${heading('THE PROJECT','Disney Antro J','A smart-village concept, brought together in one workspace.',false)}<section class="about-hero"><div class="about-monogram">DJ</div><div><span class="eyebrow">A PROJECT BY</span><h2>Disney Antro J</h2><p>Exploring how cloud technology can make essential village services easier to see, understand, and access.</p><span class="tag neutral">EDUCATIONAL PROTOTYPE · 2026</span></div></section><div class="architecture-columns"><section class="panel information-panel"><div class="panel-heading"><div><h2>Why this project?</h2></div></div><div class="prose"><p>Water supply, farming, healthcare, and education are part of everyday village life. This project shows how their information could come together in a single website.</p><p>Use the overview to compare services, explore individual pages for detail, and visit the architecture page to understand the cloud concepts.</p></div></section><section class="panel information-panel"><div class="panel-heading"><div><h2>Project details</h2></div></div><dl class="project-details"><div><dt>Site name</dt><dd>Disney Antro J</dd></div><div><dt>Project</dt><dd>Smart Village</dd></div><div><dt>Built with</dt><dd>HTML, CSS & JavaScript</dd></div><div><dt>Data</dt><dd>Simulated, for demonstration</dd></div><div><dt>Services</dt><dd>Water, agriculture, healthcare & education</dd></div></dl></section></div><section class="panel about-services"><div class="panel-heading"><div><h2>Four services. One clear view.</h2></div></div><div class="about-service-grid">${services.map(s=>`<a href="#${s.id}" style="${serviceStyle(s)}"><span class="service-icon">${icon(s.icon)}</span><h3>${s.name}</h3><p>${s.metric}</p><span class="link-button">Explore ${icon('arrow')}</span></a>`).join('')}</div></section><p class="reference-credit">Concept reference: <a href="https://smart-village-cloud.onrender.com/" target="_blank" rel="noopener noreferrer">Smart Village Cloud Management System ↗</a>. This is an original interface built for Disney Antro J.</p>`;}
const mobileNav=window.matchMedia('(max-width: 800px)');
function setMenu(open){
  const sidebar=document.querySelector('#sidebar');
  sidebar.classList.toggle('open',open);
  sidebar.inert=mobileNav.matches&&!open;
  document.querySelector('#menu-toggle').setAttribute('aria-expanded',String(open));
  document.querySelector('#menu-toggle').setAttribute('aria-label',open?'Close navigation':'Open navigation');
  document.querySelector('.shell').inert=mobileNav.matches&&open;
  document.body.classList.toggle('menu-open',mobileNav.matches&&open);
  if(open)sidebar.querySelector('a').focus();
}
function closeMenu(restoreFocus=false){setMenu(false);if(restoreFocus)document.querySelector('#menu-toggle').focus();}
mobileNav.addEventListener('change',()=>closeMenu());
setMenu(false);
function render(){const route=location.hash.slice(1)||'overview';state.page=Object.hasOwn(titles,route)?route:'overview';const service=services.find(s=>s.id===state.page);main.innerHTML=service?servicePage(service):state.page==='architecture'?architecturePage():state.page==='about'?aboutPage():overview();document.querySelector('#crumb').textContent=titles[state.page];document.querySelectorAll('[data-page]').forEach(a=>{const active=a.dataset.page===state.page;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});document.title=`${titles[state.page]} | Disney Antro J`;}
function setRange(days){if(![7,30].includes(days))throw new Error('Choose a period of 7 or 30 days.');state.range=days;render();}
function updateDemo(){state.revision++;state.updated=new Date();for(const s of services){if(typeof s.value==='number'){s.value=Math.max(45,Math.min(96,s.value+(state.revision%2?2:-2)));s.trend=[...s.trend.slice(1),s.value];}}render();document.querySelector('#announcement').textContent='Demo readings updated. These are simulated values.';}
main.addEventListener('click',e=>{const range=e.target.closest('[data-range]');if(range){setRange(Number(range.dataset.range));main.querySelector(`[data-range="${state.range}"]`)?.focus();}if(e.target.closest('[data-action="refresh"]')){updateDemo();main.querySelector('[data-action="refresh"]')?.focus();}});
document.querySelector('#menu-toggle').addEventListener('click',()=>setMenu(true));
document.querySelector('#menu-close').addEventListener('click',()=>closeMenu(true));
document.querySelector('#sidebar').addEventListener('click',e=>{if(e.target.closest('a[href]')&&mobileNav.matches){closeMenu();main.focus({preventScroll:true});}});
document.querySelector('#nav-backdrop').addEventListener('click',()=>closeMenu(true));
document.addEventListener('keydown',e=>{
  if(!document.querySelector('#sidebar').classList.contains('open'))return;
  if(e.key==='Escape'){closeMenu(true);return;}
  if(e.key==='Tab'){
    const links=[...document.querySelectorAll('#sidebar button, #sidebar a[href]')];
    const first=links[0],last=links[links.length-1];
    if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}
    else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}
  }
});window.addEventListener('hashchange',()=>{closeMenu();render();window.scrollTo(0,0);main.focus({preventScroll:true});});drawIcons();render();

// Optional agent access uses the same actions as the visible demo controls.
const modelContext=document.modelContext;
if(modelContext?.registerTool){const lifecycle=new AbortController();const register=tool=>{try{Promise.resolve(modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};register({name:'read_village_demo',title:'Read village demo',description:'Read the current simulated service values and active view. These are not live village readings.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(input&&Object.keys(input).length)throw new Error('No parameters expected.');return{page:state.page,periodDays:state.range,simulated:true,services:services.map(s=>({service:s.name,metric:s.metric,value:s.value,unit:s.unit,status:s.status}))};}});register({name:'configure_village_view',title:'Configure village view',description:'Open a service or project page and optionally select a 7-day or 30-day chart period. Does not change data.',inputSchema:{type:'object',properties:{page:{type:'string',enum:Object.keys(titles)},periodDays:{type:'number',enum:[7,30]}},required:['page'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!Object.hasOwn(titles,input.page)||Object.keys(input).some(k=>!['page','periodDays'].includes(k)))throw new Error('Unknown page or parameter.');if(input.periodDays!==undefined&&![7,30].includes(input.periodDays))throw new Error('Choose a period of 7 or 30 days.');if(input.periodDays!==undefined)state.range=input.periodDays;history.replaceState(null,'',`#${input.page}`);render();closeMenu();return{page:state.page,periodDays:state.range};}});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
